export './colors.dart';
export './lists.dart';
export './strings.dart';
export './images.dart';
export 'package:flutter/material.dart';
export 'package:flutter/widgets.dart';
export 'package:firebase_auth/firebase_auth.dart';
//export 'package:velocity_x/velocity_x.dart';
export 'package:get/get.dart';
export 'firebase_const.dart';
// export 'package:path/path.dart';
// export 'package:seller_app/views/widgets/loadiing_indicator.dart';
// export 'package:seller_app/const/const.dart';
// export 'package:seller_app/controllers/auth_controller.dart';
// export 'package:seller_app/views/home_scrn/home.dart';
// export 'package:seller_app/views/widgets/normal_text.dart';
// export 'package:seller_app/views/widgets/our_button.dart';
// export 'package:seller_app/const/firebase_const.dart';
// export 'package:seller_app/views/widgets/appbar_widget.dart';
// export 'package:seller_app/views/widgets/dashboard_button.dart';
// export 'package:seller_app/controllers/home_controller.dart';
// export 'package:seller_app/views/home_scrn/Home_Screeen.dart';
// export 'package:seller_app/views/order_screen/order_screen.dart';
// export 'package:seller_app/views/product_screen/product_screen.dart';
// export 'package:seller_app/views/profile_screen/profile_screen.dart';
// export 'package:seller_app/views/messages_screen/comp/chat_bubble.dart';
// export 'package:seller_app/views/messages_screen/chat_screen.dart';
// export 'package:seller_app/views/order_screen/comp/order_place.dart';
// export 'package:seller_app/views/order_screen/order_details.dart';
// export 'package:seller_app/views/product_screen/comp/product_dropdownn.dart';
// export 'package:seller_app/views/product_screen/comp/product_img.dart';
// export 'package:seller_app/views/widgets/custom_textfiled.dart';
// export 'package:seller_app/views/product_screen/add_product.dart';
// export 'package:seller_app/views/product_screen/product_details.dart';
// export 'package:seller_app/views/messages_screen/messages_screen.dart';
// export 'package:seller_app/views/profile_screen/edit_profile_screen.dart';
// export 'package:seller_app/views/shop_screen/shop_setting_screen.dart';