name: seller_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  get: ^4.6.6
  getx_screen: ^1.0.0
  image_picker: ^1.1.1
  velocity_x: 3.5.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - lib/services/category_model.json
